name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-88-237-125.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/var/www/html/"
