name: Push-to-EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Clean target directory on EC2
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -i ./ssh_key.pem ubuntu@ec2-3-88-237-125.compute-1.amazonaws.com 'rm -rf /var/www/html/*'

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-88-237-125.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "./"
          target: "/var/www/html/"
          port: 22